name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs: 
  flutter_build_android:
    name: Build Flutter (android) apps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: "11.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: cd frontend
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

  flutter_build_ios:
    name: Build Flutter (iOS) apps
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
    - run: flutter clean
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign

 